### ISSUE TITLE
'returningGenerated' compilation results in AssertionError

### ISSUE THREAD

**Issue by sviezypan** [zio/zio-protoquill#22] opened 2021-09-21 15:41 UTC
**Version**: `3.7.2.Beta1.4`
**Module**: `quill-jdbc-zio`
**Database**: `postgresql`)

Hello, I have a simple case class with id and some string data. I am inserting it as a row to postgresql and I would like to use returningGenerated method to have generated id back.

Following code generates compile time query INSERT INTO SomeItems (desc) VALUES (?)

  ```
final case class SomeItem(id: Int, desc: String)
def insert(description: String): ZIO[QConnection, SQLException, RunActionResult] =
    Ctx.run(quote {
        query[SomeItem].insert(_.desc -> lift(description))
      })
```

however when I try returningGenerated I am getting 
java.lang.AssertionError: assertion failed
```
def insertWithIdReturned(description: String): ZIO[QConnection, SQLException, Int] =
    Ctx.run(quote {
        query[SomeItem].insert(lift(SomeItem(0, "hohoooo"))).returningGenerated(_.id)
      })
```

### Here is reproduced issue in scastie. If you comment out method 'saveWithIdReturned', code compiles fine.
https://scastie.scala-lang.org/7f1NMFvRT7G1fIrbiKj1cA

Attached in "assertions_error.txt" is compile time error I am getting.
[assertions_error.txt](https://github.com/getquill/protoquill/files/7204420/assertions_error.txt)

@getquill/maintainers

**Comment by deusaquilus** [comment] 2021-12-07 11:48
@sviezypan @ajrnz I tried a bunch of things but I can't reproduce this issue outside of scastie. Could you please post a github repo of it?

**Comment by Quafadas** [comment] 2021-12-07 12:26
I _think_ I have a manifestation of this here; 

[Uncomment this line](https://github.com/Quafadas/scala3-full-stack-example/blob/3d6f1d5d62fe6f57038baa57da29ff6a809557f3/webserver/src/main/scala/example/DB.scala#L58)

For me, successful query compilation appears in VSCode / metals as info messages. This query appears to fail compilation. 
![image](https://user-images.githubusercontent.com/24899792/145028238-87e486fd-74c9-4cd4-98cf-3636eb360345.png)

```
git clone https://github.com/Quafadas/scala3-full-stack-example.git
```
then
```
sbt
project webserver
compile
```
This will work as is. Uncommet line 58 (returning generated) in webserver/src/main/scala/example/DB.scala and for me, the issue appears.

**Comment by deusaquilus** [comment] 2021-12-07 12:47
@Quafadas Thanks for the reproduction! Could you please try to move Scala version back to 3.0.2 and un-comment that line? Will the issue still happen?

**Comment by Quafadas** [comment] 2021-12-07 12:51
@deusaquilus Yes, I tried recompiling with scala 3.0.2 and got the same.

**Comment by deusaquilus** [comment] 2021-12-07 16:07
Oh, shoot! 3.10.0.Beta1.6 was still compiled with 3.0.0 so even 3.0.2 doesn't work right. If you move your repo back to 3.0.0 it works fine. I'll try to release a ProtoQuill version with 3.0.2 as soon as I can and this problem should go away.

**Comment by Quafadas** [comment] 2021-12-07 16:42
:-)! 

For a codebase that is , pretty much by definition pushing boundaries... that sounds like an easy fix :-)... always nice - and thankyou for looking.

**Comment by deusaquilus** [comment] 2022-02-08 14:24
Going to close this for now. Please reopen if the issue continues.

**Closed by deusaquilus** 2022-02-08 14:24 UTC
